
name: "pre-release"

on:
  push:
    branches:
      - "1.19"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Setup JDK 17"
        uses: actions/setup-java@v2
        with:
          distribution: 'liberica'
          java-version: 17

      - name: "Validate gradle-wrapper"
        uses: gradle/wrapper-validation-action@v1

      - name: "Grant execute permission for gradlew"
        run: chmod +x gradlew

      - name: "Build with Gradle"
        run: ./gradlew build

      - name: "Upload build artifacts"
        uses: actions/upload-artifact@v2
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Auto Build"
          files: 'build/libs/*.jar;!build/libs/*-sources.jar'
